cmdb/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Time    : 2019/1/4 15:16
# @Author  : WangKang

from django.conf.urls import url, include
from cmdb import views
urlpatterns = [
    url(r'^host', views.host, name="host"),
    url(r'^add_host', views.add_host, name="add_host"),
]

wuwei/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from cmdb.views import host
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'issue/', include("file_issue.urls")),
    url(r'cmdb/', include("cmdb.urls")),
    url(r'users/', include("users.urls")),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'task/', include("task.urls")),
    url(r'^index', views.index, name='index'),
    url(r'^$', host, name='home')
]

cmdb/models.py
from django.db import models
import django.utils.timezone as timezone
# Create your models here.

class Host(models.Model):
    HOST_STATUS = ((0, '正常'), (1, '不可达'))
    ASSET_STATUS = ((0, '在线'), (1, '测试'), (2, '闲置'), (3, '保修'))
    host_name=models.CharField(max_length=64)
    ip=models.CharField(max_length=32, null=False)
    host_status=models.IntegerField(choices=HOST_STATUS, default=1)
    assets_stauts=models.IntegerField(choices=ASSET_STATUS)
    opm_name=models.CharField(max_length=32, null=False)
    idc=models.CharField(max_length=64)
    time=models.DateTimeField(default=timezone.now)
    remark=models.CharField(max_length=128) # 备注

    def __unicode__(self):
        return self.host_name

class Record(models.Model):
    '''操作记录表'''
    hosts =  models.TextField(null=False)
    module = models.CharField(max_length=32, null=False)
    module_args = models.CharField(max_length=128)
    result = models.TextField(default="")
    time = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.hosts

cmdb/views.py
from cmdb import models
from django.http import HttpResponse
from ansible_api.ans_api import MyRunner
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required   # 用户登录

import os
import json
import time


@login_required(login_url='/users/login/', redirect_field_name='next')
def host(request):

    hosts_obj = models.Host.objects.all().order_by('id')
    # print(hosts_obj)
    return render(request, "cmdb/host.html", {"hosts_obj": hosts_obj})

@login_required(login_url='/users/login/', redirect_field_name='next')
def add_host(request):
    if request.method == "POST":
        print(request.POST)
        host_obj = models.Host(host_name=request.POST['hostname'], ip=request.POST['ip'], opm_name=request.POST['ompname'],
                                   assets_stauts=request.POST['assets_stauts'], idc=request.POST['idc'],
                                   remark=request.POST['remark'])
        copy_key = 'sshpass -p "%s" ssh-copy-id -i %s root@%s' % (request.POST['passwd'],
                                                                  '/root/.ssh/id_rsa.pub',
                                                                  request.POST['ip'])
        ip = request.POST['ip']
        ssh_key = os.system(copy_key)

        if ssh_key == 0:
            # 调用ansible api
            ansible = MyRunner(ip + ',')
            ansible.run(ip + ',', 'ping', '')
            result = ansible.get_result()
            if ip in json.dumps(result['success']):
                host_obj.host_status=0
                print("%s is ok!" % ip)
            else:
                print("ping loss!")

        host_obj.save()
        return redirect("/cmdb/host")
    return render(request, "cmdb/add_host.html",)

templates/cmdb/add_host.html
{%  extends '../base.html' %}
{% block content %}
    <nav class="breadcrumb"><i class="Hui-iconfont"></i> <a href="/" class="maincolor">首页</a>
        <span class="c-999 en">&gt;</span>
        <span class="c-666">主机列表</span>
        <span class="c-999 en">&gt;</span>
        <span class="c-666">添加主机</span>
        <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
    <div class="Hui-article">
        <article class="cl pd-10">
            <div class="col-lg-12">
                <form action="{% url 'add_host' %}" method="post" class="form form-horizontal" id="add_host">
					<legend>添加主机</legend>
					<div class="row cl">
						<label class="form-label col-xs-4 col-sm-3">主机名：</label>
						<div class="formControls col-xs-8 col-sm-9">
							<input name="hostname" type="text" class="input-text" autocomplete="off" placeholder="主机名">
						</div>
					</div>
					<div class="row cl">
						<label class="form-label col-xs-4 col-sm-3">IP：</label>
						<div class="formControls col-xs-8 col-sm-9">
							<input name="ip" type="text" class="input-text" autocomplete="off" placeholder="IP">
						</div>
					</div>
                    <div class="row cl">
						<label class="form-label col-xs-4 col-sm-3">运维负责人：</label>
						<div class="formControls col-xs-8 col-sm-9">
							<input name="ompname" type="text" class="input-text" autocomplete="off" placeholder="运维负责人">
						</div>
					</div>
					<div class="row cl">
						<label class="form-label col-xs-4 col-sm-3">资产状态：</label>
						<div class="formControls col-xs-8 col-sm-9"> <span class="select-box">
							<select class="select" size="1" name="assets_stauts">
								<option value="0" selected="">在线</option>
								<option value="1">测试</option>
								<option value="2">闲置</option>
								<option value="3">保修</option>
							</select>
							</span> </div>
					</div>
                    <div class="row cl">
						<label class="form-label col-xs-4 col-sm-3">机房：</label>
						<div class="formControls col-xs-8 col-sm-9">
							<input name="idc" type="text" class="input-text" autocomplete="off" placeholder="机房">
						</div>
					</div>
                    <div class="row cl">
						<label class="form-label col-xs-4 col-sm-3">root密码：</label>
						<div class="formControls col-xs-8 col-sm-9">
							<input name="passwd" type="password" class="input-text" autocomplete="off" placeholder="root密码">
						</div>
					</div>
					<div class="row cl">
						<label class="form-label col-xs-4 col-sm-3">备注：</label>
						<div class="formControls col-xs-8 col-sm-9">
							<textarea class="textarea" placeholder="..." rows="" cols="" name="remark"></textarea>
						</div>
					</div>
					<div class="row cl">
						<div class="col-xs-8 col-sm-9 col-xs-offset-4 col-sm-offset-3">
							<input class="btn btn-primary radius" type="submit" value="提交">
						</div>
					</div>
				</form>
            </div>
        </article>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        function issue() {
            $.ajax({
                type: "POST",
                dataType: "text",
                url: "{% url 'file' %}",
                data: $('#file_issue').serialize(),
                success: function (result) {
                    console.log(result);
                    alert(result);
                },
                error: function () {
                    alert("文件分发错误，请联系管理员！");
                }
            });
        }
    </script>
{% endblock %}

templates/cmdb/host.html
{%  extends '../base.html' %}
{% block content %}
    <nav class="breadcrumb"><i class="Hui-iconfont"></i> <a href="/" class="maincolor">首页</a>
        <span class="c-999 en">&gt;</span>
        <span class="c-666">主机列表</span>
        <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a>
        <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px;margin-right: 3px" href="{% url 'add_host' %}" title="添加主机" >添加主机</a>
    </nav>
    <div class="Hui-article">
        <article class="cl pd-10">
            <div class="col-lg-12">
                <table class="table table-border table-bordered table-bg">
                <thead>
                    <tr><th colspan="9" scope="col">主机列表</th></tr>
                <tr class="text-c">
                    <th>ID</th>
                    <th>主机名</th>
                    <th>IP</th>
                    <th>主机状态</th>
                    <th>资产状态</th>
                    <th>运维负责人</th>
                    <th>机房</th>
                    <th>创建时间</th>
                    <th>备注</th>
                </tr>
		        </thead>
                <tbody>
                    {% for host in hosts_obj %}
                        <tr class="text-c">
                        <td>{{ host.id }}</td>
                        <td>{{ host.host_name }}</td>
                        <td>{{ host.ip }}</td>
                        <td>{{ host.get_host_status_display }}</td>
                        <td>{{ host.get_assets_stauts_display }}</td>
                        <td>{{ host.opm_name }}</td>
                        <td>{{ host.idc }}</td>
                        <td>{{ host.time | date:"Y-m-d H:i:s" }}</td>
                        <td>{{ host.remark }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
	        </table>
            </div>
        </article>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        function issue() {
            $.ajax({
                type: "POST",
                dataType: "text",
                url: "{% url 'file' %}",
                data: $('#file_issue').serialize(),
                success: function (result) {
                    console.log(result);
                    alert(result);
                },
                error: function () {
                    alert("文件分发错误，请联系管理员！");
                }
            });
        }
    </script>
{% endblock %}